# hadolint global ignore=DL3041
FROM registry.access.redhat.com/ubi9/ubi-minimal:9.6 as downloader

WORKDIR /download

RUN microdnf update -y && \
    microdnf install -y wget git curl-minimal && \
    microdnf clean all

ARG GIT_REPO=https://github.com/redhat-na-ssa/demo-ai-gitops-catalog
RUN git clone "${GIT_REPO}" demo_ops

FROM registry.access.redhat.com/ubi9/ubi-micro:9.6 as final

# install: cli tools
ADD tools-x86_64.tgz /

ENV HOME=/offline
WORKDIR /offline
COPY --from=downloader /download /offline

# Set the user to 1001
USER 1001

LABEL org.opencontainers.image.description="CLI tools required for an OpenShift disconnected install" \
      org.opencontainers.image.source=https://github.com/codekow/ocp-offline