apiVersion: v1
baseDomain: chaos.lab
metadata:
  name: sno
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  replicas: 0
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  replicas: 1
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.3.0.0/24
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
platform:
  none: {}
pullSecret: '{"auths": {"bastion-00:8443": {"auth": "aW5pdDphbG9uZ3Bhc3N3b3Jk"}}}'
sshKey: |
  ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKk5DMDFPmpzto9s5Nk1FeqrPYNttJnvW6FCWUGrbLFo cory@keepass
  ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJbbtKs6P4wpUbZxIJcEa0t0Hw0x6Tv/Ml1/J7fMRqlQ cory@kowbuntu
  ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMZCclaNu304ostULU/oHr1C25LALS4+nFSFDwO5F7EZ cory@pinky
  ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFybml+CZeJma57fvjnUKUwuSEn0JZRpa9/SAlu4t/Ct cory@skeldora
  ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBVozIG+urkwIt9isbxcg+Eqjw/9FvzRK2pfZ59CPgwh cory@kowdora
# !! Deprecated - might be a lie - trust the docs !!
# imageContentSources:
imageDigestSources:
  - mirrors:
    - bastion-00:8443/redhat/openshift/release
    source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
  - mirrors:
    - bastion-00:8443/redhat/openshift/release-images
    source: quay.io/openshift-release-dev/ocp-release
additionalTrustBundle: |
  -----BEGIN CERTIFICATE-----
  MIIDxDCCAqygAwIBAgIUDfENs6dRhMekvZiItY/oIlyUNSYwDQYJKoZIhvcNAQEL
  BQAwZDELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAlZBMREwDwYDVQQHDAhOZXcgWW9y
  azENMAsGA1UECgwEUXVheTERMA8GA1UECwwIRGl2aXNpb24xEzARBgNVBAMMCmJh
  c3Rpb24tMDAwHhcNMjYwMzI1MTU1MjU4WhcNMjkwMTEyMTU1MjU4WjBkMQswCQYD
  VQQGEwJVUzELMAkGA1UECAwCVkExETAPBgNVBAcMCE5ldyBZb3JrMQ0wCwYDVQQK
  DARRdWF5MREwDwYDVQQLDAhEaXZpc2lvbjETMBEGA1UEAwwKYmFzdGlvbi0wMDCC
  ASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALrpeNt95LPqqUcYLVsX1wm6
  TQwB6OjgFJEDktc3fWeNemGTGvX5H81QltOj8OlfF/8cbyzIMpe4mg5m6WatbOfA
  1DFV6IcsupvAm1r2fYt8JVjZgwDMtlM86zNWNY3oA1CrCJYJ+1c66vDgIU7vNini
  PAgD12AYrDSGcDCM9U+QQ6H8Xofonzn5kCp5Aeg/CROOtUou5D+dhrBjecM/SRKO
  4a18OBwhELJYl6bX9BWhoxk3D67fPD/AXiuYH0eTLzU/Z1MKID9ykqruW051BO6y
  Ib3OOqufSWu8XO5j/kMa0VIaro941HdoW8BlC+r47dlKuGbTXhaTsu6jXgbA5uEC
  AwEAAaNuMGwwCwYDVR0PBAQDAgLkMBMGA1UdJQQMMAoGCCsGAQUFBwMBMBUGA1Ud
  EQQOMAyCCmJhc3Rpb24tMDAwEgYDVR0TAQH/BAgwBgEB/wIBATAdBgNVHQ4EFgQU
  lvE+Gp+s2ceuSEOV8vs5Gns6ZMgwDQYJKoZIhvcNAQELBQADggEBALouGEwTlxlf
  z1DwuU6mWN3FtFmCIPrye11ge8rmk0LlyShFDihzbOdLXErVd8T8vrsjiKIY7RSL
  uZVhfWGYxLEQg7qHC2NMSAfyR7PLeCKfOY1UsVU5BnG6s/Lpa5CjlDlsjUJL4GzU
  /jcUE8XfVC++nsqROU3BtBqphJbVOtTQXZWPHlGlWOXib2ksShRRP7XITLqRIVlD
  bSHncFCZxxfm5d3IzX6PCXS5rKev1jSF4W9mN7GcvtfJC7+eYLSyeVR15pP9iYoT
  8Q+EqrnOuWCrBloRooiAha9h4+oRVYSJoebdkRyi5zbYMO0GhaRtpgm8vnaxOnAY
  gzlHvdv7dqs=
  -----END CERTIFICATE-----
fips: false
