---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: update-graph
  namespace: registry
spec:
  tags:
    - name: latest
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: graph-data
  namespace: registry
spec:
  output:
    to:
      # kind: DockerImage
      # name: zot-registry.registry.svc.cluster.local:5000/redhat/openshift/update-graph
      kind: ImageStreamTag
      name: 'update-graph:latest'
  runPolicy: Serial
  source:
    dockerfile: |-
      FROM registry.access.redhat.com/ubi8/ubi:8.1

      ENV GRAPH_URL=https://github.com/openshift/cincinnati-graph-data/archive/master.tar.gz
      
      RUN mkdir -p /var/lib/cincinnati/graph-data/ && \
          curl -L "${GRAPH_URL}" | tar vzx -C /var/lib/cincinnati/graph-data/ --strip-components=1

    type: Dockerfile
  strategy:
    dockerStrategy:
      # from:
      #   kind: DockerImage
      #   name: registry.access.redhat.com/ubi8/ubi:8.1
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
  - type: ConfigChange
