kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  platform:
    channels:
    - name: stable-4.20
      type: ocp
      minVersion: 4.20.15
      maxVersion: 4.20.15
    graph: true
  operators:
    - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.20
      packages:
      - name: cincinnati-operator
        defaultChannel: v1
        minVersion: 5.0.3
        maxVersion: 5.0.3
      - name: local-storage-operator
        defaultChannel: stable
        minVersion: 4.20.0-202602091941
        maxVersion: 4.20.0-202602091941
      - name: kubevirt-hyperconverged
        defaultChannel: stable
        minVersion: 4.20.7
        maxVersion: 4.20.7
      - name: web-terminal
        defaultChannel: fast
        minVersion: 1.15.0
        maxVersion: 1.15.0
      - name: power-monitoring-operator
        defaultChannel: tech-preview
        minVersion: 0.5.0
        maxVersion: 0.5.0
  additionalImages:
   - name: registry.redhat.io/ubi8/ubi:latest
   - name: registry.redhat.io/ubi9/ubi:latest
   - name: registry.redhat.io/ubi10/ubi:latest
   # add any other images that you want from registry.redhat.io, quay.io, or your public registry
   # to make them available in the disconnected environment.
