# $HOME/.config/containers/registries.conf
# https://www.redhat.com/en/blog/manage-container-registries

[[registry]]
location="registry.lab:5000"
# insecure=true

[[registry]]
prefix = "k8s.gcr.io"
location = "k8s.gcr.io"
[[registry.mirror]]
location = "registry.lab:5000/k8s.gcr.io"

[[registry]]
prefix = "ghcr.io"
location = "ghcr.io"
[[registry.mirror]]
location = "registry.lab:5000/ghcr.io"

[[registry]]
prefix = "quay.io"
location = "quay.io"
[[registry.mirror]]
location = "registry.lab:5000/quay.io"

[[registry]]
prefix = "registry.access.redhat.com"
location = "registry.access.redhat.com"
[[registry.mirror]]
location = "registry.lab:5000/registry.access.redhat.com"

[[registry]]
prefix = "registry.connect.redhat.com"
location = "registry.connect.redhat.com"
[[registry.mirror]]
location = "registry.lab:5000/registry.connect.redhat.com"

[[registry]]
prefix = "registry.redhat.io"
location = "registry.redhat.io"
[[registry.mirror]]
location = "registry.lab:5000/registry.redhat.io"
