---
apiVersion: olm.operatorframework.io/v1
kind: ClusterCatalog
metadata:
  name: cc-redhat-operator-index-v4-20
spec:
  priority: 0
  source:
    image:
      ref: bootstrap-00:8443/redhat/redhat/redhat-operator-index:v4.20
    type: Image
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: cs-redhat-operator-index-v4-20
  namespace: openshift-marketplace
spec:
  image: bootstrap-00:8443/redhat/redhat/redhat-operator-index:v4.20
  sourceType: grpc
